package net.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.kehui.www.t_907_origin.datebase.UserDate;

import net.dao.UserDateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDateDaoConfig;

    private final UserDateDao userDateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDateDaoConfig = daoConfigMap.get(UserDateDao.class).clone();
        userDateDaoConfig.initIdentityScope(type);

        userDateDao = new UserDateDao(userDateDaoConfig, this);

        registerDao(UserDate.class, userDateDao);
    }
    
    public void clear() {
        userDateDaoConfig.clearIdentityScope();
    }

    public UserDateDao getUserDateDao() {
        return userDateDao;
    }

}
